version: '3.1'
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: comp4111
      MYSQL_DATABASE: comp4111
      MYSQL_USER: comp4111
      MYSQL_PASSWORD: comp4111
  api:
    build: .
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      PORT: 80
      DB_URL: mysql://db:3306/comp4111?user=comp4111&password=comp4111&useSSL=false
